### ISSUE TITLE
[shim] tests currently failing on Node < 10

### ISSUE THREAD

**Issue by warner** [tc39/proposal-realms#105]
Looks like the latest change to the shim broke the test suite on all but the most recent version of Node

https://travis-ci.com/tc39/proposal-realms/builds/75163904

```
$ tape -r esm ./shim/test/**/*.js
TAP version 13
# confinement evaluation strict mode
SyntaxError: Unexpected token *
    at eval (<anonymous>)
    at repairFunction (/home/travis/build/tc39/proposal-realms/shim/src/functions.js:21:24)
    at repairFunctions (/home/travis/build/tc39/proposal-realms/shim/src/functions.js:61:3)
    at sanitize (/home/travis/build/tc39/proposal-realms/shim/src/sanitize.js:11:3)
    at createContextRec (/home/travis/build/tc39/proposal-realms/shim/src/context.js:48:3)
    at new Realm (/home/travis/build/tc39/proposal-realms/shim/src/realm.js:108:20)
    at Test.require.t (/home/travis/build/tc39/proposal-realms/shim/test/realm/confinement.js:7:13)
    at Test.bound [as _cb] (/home/travis/build/tc39/proposal-realms/node_modules/tape/lib/test.js:77:32)
    at Test.run (/home/travis/build/tc39/proposal-realms/node_modules/tape/lib/test.js:96:10)
    at Test.bound [as run] (/home/travis/build/tc39/proposal-realms/node_modules/tape/lib/test.js:77:32)
error Command failed with exit code 1.
```

I'm guessing that something is using a `function*` (probably to reach the generator-function intrinsic, to wrap it) without first checking that the current environment even supports that syntax.

**Comment by warner** [comment]
Ah, found it, identity-discontinuity strikes again: the code that tests for the new syntax was comparing `SyntaxError` objects from different Realms. PR to follow.
