### ISSUE TITLE
[shim] add support for node

### ISSUE THREAD

**Issue by caridy** [tc39/proposal-realms#24]

**Comment by ajvincent** [comment]
This could be a blocker for https://github.com/ajvincent/es7-membrane/issues/61 .

**Comment by ajvincent** [comment]
Suggestion:
1. Write a new module at shim/src/nodeGlobal.js
2. In the module file, manually write a barebones membrane whose only purpose is to reject delete or defineProperty operations.
3. The module's sole export is a wrapped global object.

**Comment by erights** [comment]
When I follow the instructions on https://github.com/tc39/proposal-realms/tree/master/shim I get the following error. Searching on the first line seems to indicate that the problem has to do with babel-preset-es2015-rollup but I cannot figure it out.


proposal-realms:0:$ npm run build-shim-dev

> ecma-proposal-realms@0.0.0 build-shim-dev /Users/erights/src/ongithub/proposal-realms
> node shim/rollup.config.js

building...
node_modules/nan
resolve failed:  { Error: Cannot find module 'babel-runtime'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.requireRelative.resolve (/Users/erights/src/ongithub/proposal-realms/node_modules/require-relative/index.js:30:17)
    at resolve (/Users/erights/src/ongithub/proposal-realms/node_modules/modify-babel-preset/lib/serialize.js:25:26)
    at findAndRemove (/Users/erights/src/ongithub/proposal-realms/node_modules/modify-babel-preset/lib/serialize.js:67:11)
    at /Users/erights/src/ongithub/proposal-realms/node_modules/modify-babel-preset/lib/serialize.js:111:13
    at Array.map (native)
    at loadPreset (/Users/erights/src/ongithub/proposal-realms/node_modules/modify-babel-preset/lib/serialize.js:103:29)
    at module.exports (/Users/erights/src/ongithub/proposal-realms/node_modules/modify-babel-preset/index.js:97:19)
    at Object.<anonymous> (/Users/erights/src/ongithub/proposal-realms/node_modules/babel-preset-es2015-rollup/index.js:3:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19) code: 'MODULE_NOT_FOUND' } babel-runtime

**Comment by erights** [comment]
attn @caridy @dherman

**Comment by caridy** [comment]
@erights I have fixed the build process, you should be able to install it now. Make sure you nuke your `node_modules` folder and reinstall it again before running the build step.

**Comment by koba04** [comment]
The shim seems to have Node support.

https://github.com/tc39/proposal-realms/commit/b85c75c144d3b71ca4b8f925fd302ce18ac9f904#diff-5d9e844ec1eec5451132dd46a4cbc9a7

**Comment by caridy** [comment]
yeah, I think we can close this one, and reopen it if needed.
